# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlmoFire API Calling Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlmoFire API Calling Example

pod 'Alamofire'
pod 'ReachabilitySwift', '~> 3'
end
